sudo: required
services:
  - docker
env:
  - TYPO3_VERSION=8
  - TYPO3_VERSION=9
  - TYPO3_VERSION=10

script:
  - docker-compose build --build-arg TYPO_VERSION=$TYPO3_VERSION
  - docker-compose up -d
  - sleep 10
  - curl -vf http://localhost/typo3/install.php || curl -v http://localhost/typo3/install/
